### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by drnic** [logsearch/logsearch-for-cloudfoundry#11]
```
$ ./bin/build-and-test.sh 
===> Building ...
===> Testing ...
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch=>true, :broken=>true}
.........F

Failures:

  1) LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "2014-04-24T04:03:06.000Z", but got "2015-04-24T04:03:06.000Z"
     # ./test/logstash/snippets/vcap-spec.rb:72:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:154:in `run'

Finished in 23.53 seconds
10 examples, 1 failure

Failed examples:

rspec ./vendor/logstash/spec/test_utils.rb:94 # LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed
```

**Comment by devcamcar** [comment]
I just ran into the same

**Comment by devcamcar** [comment]
PR up for this: https://github.com/logsearch/logsearch-filters-cf/pull/12

**Comment by mrdavidlaing** [comment]
All tests are now passing
